"""Turns a training checkpoint into a submittable C++ bot, then holds it to
the export gate.

    python -m export.export_bot --checkpoint checkpoints/run1/latest.pt --out bots/rl_bot_v2
    unswbc run maps/arena.map bots/rl_bot_v2 bots/rl_bot_v2 --sandbox -v
    unswbc submit bots/rl_bot_v2

The bot is export/bot/main.cpp and net.h, the shared core's view.h and
features.h copied in unchanged (the files training compiles), and a
generated weights.h holding the integer actor (export/quantize.py).
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import shutil

import numpy as np
import torch

import bccore
from rl.policy import Actor

from .quantize import IntegerActor, quantize

ROOT = pathlib.Path(__file__).resolve().parents[1]
BOT_SOURCES = ROOT / "export" / "bot"
CORE = ROOT / "core" / "include" / "core"
SHARED = ("view.h", "features.h")


def load_actor(checkpoint: str) -> tuple[Actor, dict]:
    state = torch.load(checkpoint, map_location="cpu", weights_only=False)
    actor = Actor(bccore.OBS_SIZE, bccore.NUM_ACTIONS, bccore.feature_scales(), tuple(state["hidden"]))
    actor.load_state_dict(state["actor"])
    actor.qat = bool(state.get("qat", False))
    actor.eval()
    return actor, state


def _pad(n: int, to: int = 16) -> int:
    return (n + to - 1) // to * to


def _array(name: str, ctype: str, values: np.ndarray, suffix: str = "") -> str:
    body = ",".join(f"{int(v)}{suffix}" for v in values.ravel())
    return f"alignas(16) static {ctype} const {name}[] = {{{body}}};\n"


def weights_header(integer: IntegerActor, mask_level: int, source: str) -> str:
    layers = integer.layers
    rows = [layer.weight.shape[0] for layer in layers]
    strides = [_pad(layer.weight.shape[1]) for layer in layers]
    out = [
        "#pragma once\n",
        f"// Generated by export/export_bot.py from {source}. Do not edit.\n",
        "#include <cstdint>\n\n",
        f"constexpr int kInputs = {layers[0].weight.shape[1]};\n",
        f"constexpr int kOutputs = {rows[-1]};\n",
        f"constexpr int kLayers = {len(layers)};\n",
        f"constexpr int kMaskLevel = {mask_level};\n",
        f"constexpr int kRows[kLayers] = {{{', '.join(map(str, rows))}}};\n",
        f"constexpr int kStride[kLayers] = {{{', '.join(map(str, strides))}}};\n",
        f"constexpr int kMaxWidth = {max(strides + [_pad(r) for r in rows])};\n\n",
    ]
    for i, (layer, stride) in enumerate(zip(layers, strides)):
        padded = np.zeros((layer.weight.shape[0], stride), dtype=np.int8)
        padded[:, :layer.weight.shape[1]] = layer.weight
        out.append(_array(f"kW{i}", "int8_t", padded))
        out.append(_array(f"kB{i}", "int32_t", layer.bias))
        if layer.multiplier is not None:
            out.append(_array(f"kM{i}", "int64_t", layer.multiplier, "LL"))
    n = len(layers)
    out.append(f"static int8_t const* const kWeights[kLayers] = {{{', '.join(f'kW{i}' for i in range(n))}}};\n")
    out.append(f"static int32_t const* const kBias[kLayers] = {{{', '.join(f'kB{i}' for i in range(n))}}};\n")
    mults = ", ".join(f"kM{i}" if layers[i].multiplier is not None else "nullptr" for i in range(n))
    out.append(f"static int64_t const* const kMultiplier[kLayers] = {{{mults}}};\n")
    return "".join(out)


def write_bot(integer: IntegerActor, mask_level: int, out_dir: pathlib.Path, source: str):
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "core").mkdir(exist_ok=True)
    for name in SHARED:
        shutil.copyfile(CORE / name, out_dir / "core" / name)
    for name in ("main.cpp", "net.h"):
        shutil.copyfile(BOT_SOURCES / name, out_dir / name)
    (out_dir / "weights.h").write_text(weights_header(integer, mask_level, source))
    (out_dir / "bot.toml").write_text(
        '# written by export/export_bot.py\n[project]\nlanguage = "cpp"\ninclude = [ "*.cpp", "*.h" ]\n')
    (out_dir / ".gitignore").write_text(".unswbc-build/\n")


def shared_files_match(bot_dir: pathlib.Path) -> bool:
    """The bot's copies of the shared core are the files training compiles."""
    digest = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()  # noqa: E731
    return all(digest(bot_dir / "core" / name) == digest(CORE / name) for name in SHARED)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--checkpoint", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--no-gate", action="store_true", help="skip the export gate")
    p.add_argument("--gate-games", type=int, default=24)
    p.add_argument("--no-sandbox", action="store_true", help="gate natively only")
    args = p.parse_args()

    actor, state = load_actor(args.checkpoint)
    if not actor.qat:
        print("warning: this checkpoint was not trained quantisation-aware; the integer actor may differ more")
    integer = quantize(actor)
    out_dir = pathlib.Path(args.out)
    write_bot(integer, int(state.get("mask_level", 1)), out_dir, pathlib.Path(args.checkpoint).name)
    sizes = " -> ".join(map(str, integer.sizes))
    print(f"wrote {out_dir} (actor {sizes}, mask level {state.get('mask_level', 1)}, "
          f"iteration {state.get('iteration', '?')})")
    if args.no_gate:
        return
    from .gate import run_gate

    report = run_gate(out_dir, actor, integer, mask_level=int(state.get("mask_level", 1)), games=args.gate_games,
                      sandbox=not args.no_sandbox)
    print(report.summary())
    if not report.passed:
        raise SystemExit("the export gate failed: do not submit this bot")


if __name__ == "__main__":
    main()
