"""RL-trained Battlecode bot.

Generated by export/export_bot.py from a PPO checkpoint. Loads six raw
float32 weight blobs (a NumPy export of rl/policy.py's ActorCritic) and
runs the same forward pass by hand, since the judge's Python sandbox ships
only CPython 3.13 and NumPy -- no PyTorch.

Observation encoding lives in bot_encoding.py, which mirrors sim/obs.py's
layout exactly (see that file's docstring and tests/test_obs_contract.py
in the training repo).
"""
import os

import numpy as np

import helper as unswbc
from bot_encoding import DIRS, DIR_ENUM, encode_observation, safe_directions

ct: unswbc.Controller
game: unswbc.Game

# Weights ship as raw little-endian float32 blobs, not .npz: the judge
# prices every bytecode-level operation, and parsing a zip (even an
# uncompressed one) through Python's `zipfile` burns a lot more of a
# turn's CPU-point budget than a flat `np.fromfile` does.
_OBS_SIZE = 840
_HIDDEN = 256
_NUM_ACTIONS = 4
_WEIGHTS_DIR = os.path.dirname(os.path.abspath(__file__))


def _load(name: str, shape: tuple) -> np.ndarray:
    return np.fromfile(os.path.join(_WEIGHTS_DIR, name), dtype=np.float32).reshape(shape)


_W0 = _load("w0.bin", (_HIDDEN, _OBS_SIZE))
_B0 = _load("b0.bin", (_HIDDEN,))
_W2 = _load("w2.bin", (_HIDDEN, _HIDDEN))
_B2 = _load("b2.bin", (_HIDDEN,))
_WA = _load("wa.bin", (_NUM_ACTIONS, _HIDDEN))
_BA = _load("ba.bin", (_NUM_ACTIONS,))


def _policy_forward(obs: np.ndarray) -> np.ndarray:
    h = np.maximum(obs @ _W0.T + _B0, 0.0)
    h = np.maximum(h @ _W2.T + _B2, 0.0)
    return h @ _WA.T + _BA  # logits, shape (4,) in DIRS order


def execute_turn() -> None:
    obs = np.asarray(encode_observation(ct, game), dtype=np.float32)
    logits = _policy_forward(obs)

    safe = safe_directions(ct)
    if safe:
        mask = np.full(4, -np.inf, dtype=np.float32)
        for d in safe:
            mask[DIRS.index(d)] = 0.0
        logits = logits + mask

    best = int(np.argmax(logits))
    ct.make_move(DIR_ENUM[DIRS[best]])


def main() -> None:
    global ct, game
    ct, game = unswbc.init()

    while unswbc.update(ct, game):
        execute_turn()
        unswbc.end_turn()


if __name__ == "__main__":
    main()
